version: "3"
services:
  prest:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - PREST_DEBUG=true # remove comment to disable DEBUG mode
      - PREST_PG_HOST=postgres
      - PREST_PG_CACHE=false
      - PREST_JWT_DEFAULT=false # toggle to use jwt
      - PREST_CACHE_ENABLED=false
    ports:
      - "3000:3000"
    networks:
      - stg-network
networks:
  stg-network:
    external: true
